# Generated by Django 3.0.8 on 2021-07-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_assigndeassignquiz_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assigndeassignquiz',
            table='assignDeassignQuiz',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
    ]
